version: '3'


services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 1s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  elasticsearch:
    image: hypothesis/elasticsearch:latest
    ports:
      - '127.0.0.1:9200:9200'
    environment:
      - discovery.type=single-node
      - bootstrap.system_call_filter=false
      - network.host=0.0.0.0
      - ES_JAVA_OPTS= -Xms400m -Xmx400m
  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
